apiVersion: v1
kind: Pod
metadata:
  name: etcd-version-monitor
  namespace: kube-system
spec:
  hostNetwork: true
  nodeSelector:
    beta.kubernetes.io/os: linux
  containers:
  - name: etcd-version-monitor
    image: k8s.gcr.io/etcd-version-monitor:0.1.2
    command:
    - /etcd-version-monitor
    - --logtostderr
